-- Clear existing data
TRUNCATE public.epidemic_alerts CASCADE;
TRUNCATE public.disease_reports CASCADE;
TRUNCATE public.diseases CASCADE;

INSERT INTO public.diseases (name, description, symptoms, precautions, medications, severity, is_communicable, transmission_rate) VALUES
-- RESPIRATORY & INFECTIONS
('Common Cold', 'Mild viral infection of the upper respiratory tract.', ARRAY['runny nose', 'sneezing', 'sore throat', 'cough', 'congestion', 'mild fever', 'watery eyes', 'hoarseness', 'post-nasal drip'], ARRAY['rest', 'stay hydrated', 'wash hands frequently', 'avoid close contact with sick people'], ARRAY['paracetamol', 'antihistamines', 'decongestants', 'vitamin C'], 'mild', true, 0.85),
('Influenza (Flu)', 'Contagious respiratory illness caused by influenza viruses.', ARRAY['high fever', 'chills', 'severe body aches', 'fatigue', 'dry cough', 'headache', 'sore throat', 'runny nose', 'sweating'], ARRAY['get annual flu vaccine', 'wash hands', 'stay home when sick', 'cover coughs and sneezes'], ARRAY['oseltamivir', 'paracetamol', 'ibuprofen', 'rest and fluids'], 'moderate', true, 0.70),
('COVID-19', 'Respiratory illness caused by SARS-CoV-2 coronavirus.', ARRAY['dry cough', 'fever', 'shortness of breath', 'fatigue', 'loss of taste', 'loss of smell', 'body aches', 'sore throat', 'diarrhea', 'chest pressure'], ARRAY['wear mask', 'maintain social distance', 'isolation if positive', 'get vaccinated', 'wash hands'], ARRAY['paracetamol', 'antivirals', 'corticosteroids', 'oxygen therapy'], 'severe', true, 0.95),
('Pneumonia', 'Infection that inflames air sacs in one or both lungs.', ARRAY['chest pain when breathing', 'cough with greenish phlegm', 'fever', 'chills', 'difficulty breathing', 'fatigue', 'nausea', 'rapid heartbeat'], ARRAY['get vaccinated', 'quit smoking', 'avoid sick contacts'], ARRAY['amoxicillin', 'azithromycin', 'cefuroxime', 'paracetamol', 'ibuprofen'], 'severe', true, 0.40),
('Bronchitis', 'Inflammation of the lining of bronchial tubes.', ARRAY['cough with clear or yellow mucus', 'chest tightness', 'shortness of breath', 'mild fever', 'fatigue', 'sore throat', 'wheezing'], ARRAY['avoid cigarette smoke', 'wear a mask', 'stay hydrated'], ARRAY['cough expectorants', 'bronchodilators', 'paracetamol'], 'moderate', true, 0.35),
('Asthma', 'Chronic condition causing airway inflammation and narrowing.', ARRAY['wheezing', 'shortness of breath', 'chest tightness', 'cough (especially at night)', 'breathlessness on exertion'], ARRAY['identify triggers', 'keep inhaler handy', 'monitor peak flow', 'air purifier indoors'], ARRAY['salbutamol inhaler', 'beclomethasone inhaler', 'montelukast'], 'moderate', false, 0.00),
('Tuberculosis (TB)', 'Bacterial infection primarily affecting the lungs.', ARRAY['persistent cough', 'coughing blood', 'night sweats', 'fever', 'unexplained weight loss', 'fatigue', 'chest pain', 'loss of appetite'], ARRAY['complete antibiotics', 'wear mask', 'improve ventilation', 'BCG vaccination'], ARRAY['isoniazid', 'rifampicin', 'ethambutol', 'pyrazinamide'], 'critical', true, 0.30),
('Pertussis (Whooping Cough)', 'Highly contagious bacterial tract infection.', ARRAY['severe coughing fits', 'whoop sound', 'runny nose', 'mild fever', 'apnea', 'vomiting after coughing'], ARRAY['DTaP vaccine', 'isolation', 'cover coughs'], ARRAY['azithromycin', 'clarithromycin', 'erythromycin'], 'severe', true, 0.85),
('Strep Throat', 'Bacterial infection causing a severe sore throat.', ARRAY['sudden severe sore throat', 'pain when swallowing', 'fever', 'red and swollen tonsils', 'white patches on tonsils', 'swollen lymph nodes'], ARRAY['wash hands', 'do not share utensils', 'replace toothbrush'], ARRAY['penicillin', 'amoxicillin', 'ibuprofen'], 'moderate', true, 0.60),
('Sinusitis', 'Inflammation of the sinuses.', ARRAY['facial pain', 'facial pressure', 'nasal congestion', 'thick nasal discharge', 'loss of smell', 'headache', 'toothache', 'bad breath'], ARRAY['nasal irrigation', 'steam inhalation', 'stay hydrated', 'rest'], ARRAY['amoxicillin', 'nasal corticosteroids', 'decongestants'], 'mild', false, 0.10),

-- VECTOR-BORNE & TROPICAL
('Malaria', 'Parasitic disease transmitted by mosquitoes.', ARRAY['high fever', 'chills', 'shaking', 'profuse sweating', 'headache', 'nausea', 'vomiting', 'muscle pain', 'anaemia', 'jaundice'], ARRAY['use mosquito nets', 'wear long sleeves', 'use DEET', 'antimalarial prophylaxis'], ARRAY['artemether-lumefantrine', 'chloroquine', 'primaquine'], 'severe', false, 0.00),
('Dengue Fever', 'Viral disease spread by Aedes mosquitoes.', ARRAY['sudden high fever', 'severe headache', 'pain behind eyes', 'severe joint pain', 'muscle pain', 'skin rash', 'mild bleeding', 'nausea', 'extreme fatigue'], ARRAY['eliminate standing water', 'use mosquito repellent', 'window screens'], ARRAY['paracetamol', 'oral rehydration', 'IV fluids'], 'severe', false, 0.00),
('Chikungunya', 'Viral disease transmitted by Aedes mosquitoes.', ARRAY['sudden fever', 'severe debilitating joint pain', 'joint swelling', 'muscle pain', 'headache', 'maculopapular rash', 'fatigue'], ARRAY['use insect repellent', 'wear long sleeves', 'eliminate standing water'], ARRAY['paracetamol', 'naproxen', 'ibuprofen'], 'moderate', false, 0.00),
('Zika Virus', 'Viral disease spread by mosquitoes.', ARRAY['mild fever', 'rash', 'conjunctivitis', 'muscle pain', 'joint pain', 'headache'], ARRAY['prevent mosquito bites', 'safe sex practices', 'avoid travel if pregnant'], ARRAY['paracetamol', 'rest', 'fluids'], 'mild', true, 0.10),
('Lyme Disease', 'Bacterial infection spread by ticks.', ARRAY['bullseye rash', 'fever', 'chills', 'fatigue', 'body aches', 'swollen lymph nodes', 'joint pain', 'neurological problems'], ARRAY['wear long pants', 'use tick repellent', 'check for ticks', 'remove ticks promptly'], ARRAY['doxycycline', 'amoxicillin', 'cefuroxime axetil'], 'moderate', false, 0.00),
('Yellow Fever', 'Viral hemorrhagic disease transmitted by mosquitoes.', ARRAY['fever', 'headache', 'jaundice', 'muscle pain', 'nausea', 'vomiting', 'fatigue'], ARRAY['Yellow fever vaccine', 'mosquito control'], ARRAY['supportive care', 'IV fluids', 'paracetamol'], 'critical', false, 0.00),
('Typhus', 'Bacterial disease spread by lice or fleas.', ARRAY['fever', 'headache', 'rash', 'chills', 'muscle aches', 'confusion'], ARRAY['avoid rat fleas', 'improve hygiene', 'insect repellent'], ARRAY['doxycycline', 'chloramphenicol'], 'severe', false, 0.00),

-- GASTROINTESTINAL & DIGESTIVE
('Food Poisoning', 'Illness from contaminated food.', ARRAY['nausea', 'vomiting', 'watery diarrhea', 'stomach cramps', 'mild fever', 'weakness', 'loss of appetite'], ARRAY['eat safe food', 'refrigerate properly', 'wash hands', 'avoid raw shellfish'], ARRAY['oral rehydration salts', 'ondansetron', 'antibiotics if severe'], 'mild', false, 0.00),
('Cholera', 'Acute diarrheal infection caused by Vibrio cholerae.', ARRAY['profuse watery diarrhea', 'vomiting', 'severe leg cramps', 'rapid dehydration', 'rapid heart rate', 'low blood pressure', 'extreme thirst'], ARRAY['drink treated water', 'food hygiene', 'hand washing', 'vaccine'], ARRAY['oral rehydration solution', 'doxycycline', 'azithromycin'], 'critical', true, 0.60),
('Typhoid Fever', 'Bacterial infection by Salmonella typhi.', ARRAY['prolonged high fever', 'extreme fatigue', 'stomach pain', 'constipation', 'headache', 'loss of appetite', 'rose spots', 'diarrhea'], ARRAY['drink treated water', 'sanitation', 'hand washing', 'vaccination'], ARRAY['ciprofloxacin', 'azithromycin', 'ceftriaxone'], 'moderate', true, 0.20),
('Gastroenteritis (Stomach Flu)', 'Inflammation of stomach and intestines.', ARRAY['watery diarrhea', 'vomiting', 'stomach cramps', 'nausea', 'low-grade fever', 'headache', 'muscle aches'], ARRAY['hand washing', 'safe food handling', 'disinfect surfaces'], ARRAY['oral rehydration salts', 'ondansetron', 'loperamide'], 'mild', true, 0.55),
('Peptic Ulcer', 'Sores on the lining of the stomach.', ARRAY['burning stomach pain', 'feeling of fullness', 'bloating', 'burping', 'intolerance to fatty foods', 'heartburn', 'nausea', 'dark tarry stools'], ARRAY['avoid NSAIDs', 'avoid alcohol', 'eat smaller meals', 'avoid spicy food'], ARRAY['omeprazole', 'pantoprazole', 'antacids', 'amoxicillin'], 'moderate', false, 0.00),
('Appendicitis', 'Inflammation of the appendix.', ARRAY['sudden pain on right side of lower abdomen', 'nausea', 'vomiting', 'loss of appetite', 'fever', 'constipation', 'abdominal bloating'], ARRAY['seek emergency medical care immediately'], ARRAY['surgery (appendectomy)', 'IV antibiotics', 'pain relievers'], 'critical', false, 0.00),
('Hepatitis A', 'Highly contagious liver infection.', ARRAY['fatigue', 'nausea', 'abdominal pain', 'loss of appetite', 'low-grade fever', 'dark urine', 'joint pain', 'jaundice'], ARRAY['Hepatitis A vaccine', 'wash hands', 'avoid unclean water'], ARRAY['rest', 'hydration', 'avoid alcohol'], 'moderate', true, 0.70),
('Hepatitis B', 'Serious liver infection.', ARRAY['abdominal pain', 'dark urine', 'fever', 'joint pain', 'loss of appetite', 'nausea', 'vomiting', 'weakness', 'jaundice'], ARRAY['Hepatitis B vaccine', 'safe sex practices', 'avoid sharing needles'], ARRAY['entecavir', 'tenofovir', 'interferon injections'], 'severe', true, 0.40),
('Hepatitis C', 'Viral infection causing liver inflammation.', ARRAY['bleeding easily', 'bruising easily', 'fatigue', 'poor appetite', 'jaundice', 'dark urine', 'itchy skin', 'fluid buildup in abdomen'], ARRAY['avoid sharing needles', 'safe sex practices'], ARRAY['sofosbuvir', 'velpatasvir', 'glecaprevir'], 'severe', true, 0.30),
('Celiac Disease', 'Immune reaction to eating gluten.', ARRAY['diarrhea', 'fatigue', 'weight loss', 'bloating', 'gas', 'abdominal pain', 'nausea', 'constipation', 'vomiting'], ARRAY['strict gluten-free diet', 'vitamin supplementation'], ARRAY['dietary management', 'steroids for severe inflammation'], 'moderate', false, 0.00),
('Crohns Disease', 'Inflammatory bowel disease.', ARRAY['diarrhea', 'fever', 'fatigue', 'abdominal pain', 'cramping', 'blood in stool', 'mouth sores', 'reduced appetite', 'weight loss'], ARRAY['manage stress', 'dietary changes', 'quit smoking'], ARRAY['corticosteroids', 'azathioprine', 'infliximab'], 'severe', false, 0.00),
('Ulcerative Colitis', 'Inflammatory bowel disease affecting colon.', ARRAY['diarrhea with blood or pus', 'abdominal pain', 'cramping', 'rectal pain', 'rectal bleeding', 'urgency to defecate', 'weight loss', 'fatigue', 'fever'], ARRAY['dietary management', 'stress management'], ARRAY['mesalamine', 'corticosteroids', 'cyclosporine'], 'severe', false, 0.00),
('Irritable Bowel Syndrome (IBS)', 'Common disorder of the large intestine.', ARRAY['cramping', 'abdominal pain', 'bloating', 'gas', 'diarrhea', 'constipation', 'mucus in stool'], ARRAY['avoid trigger foods', 'eat high-fiber foods', 'drink plenty of fluids', 'exercise regularly'], ARRAY['fiber supplements', 'laxatives', 'anti-diarrheal medications', 'antispasmodics'], 'mild', false, 0.00),

-- SKIN / DERMATOLOGICAL
('Chickenpox', 'Highly contagious viral infection.', ARRAY['itchy blister rash', 'fever', 'tiredness', 'loss of appetite', 'headache', 'red spots on skin', 'scabbing'], ARRAY['vaccination', 'isolate infected person', 'trim nails short'], ARRAY['acyclovir', 'calamine lotion', 'antihistamines'], 'moderate', true, 0.90),
('Measles', 'Contagious viral infection.', ARRAY['high fever', 'dry cough', 'runny nose', 'red watery eyes', 'white spots in mouth', 'widespread skin rash', 'sensitivity to light'], ARRAY['MMR vaccination', 'isolate', 'Vitamin A supplementation'], ARRAY['paracetamol', 'Vitamin A', 'supportive care'], 'severe', true, 0.90),
('Scabies', 'Skin infestation caused by mites.', ARRAY['intense itching', 'thin irregular burrow lines', 'pimple-like skin rash', 'sores from scratching'], ARRAY['treat household members', 'wash bedding in hot water', 'avoid skin-to-skin contact'], ARRAY['permethrin cream', 'ivermectin', 'antihistamines'], 'mild', true, 0.60),
('Ringworm', 'Fungal infection of the skin.', ARRAY['ring-shaped red rash', 'itching', 'scaly skin', 'overlapping rings', 'hair loss'], ARRAY['keep skin clean and dry', 'do not share clothing', 'wear shoes in public showers'], ARRAY['clotrimazole', 'miconazole', 'terbinafine'], 'mild', true, 0.30),
('Psoriasis', 'Skin disease causing red, itchy scaly patches.', ARRAY['red patches of skin covered with thick silvery scales', 'small scaling spots', 'dry cracked skin', 'itching', 'burning', 'soreness', 'swollen joints'], ARRAY['avoid triggers', 'moisturize daily', 'moderate sun exposure'], ARRAY['topical corticosteroids', 'vitamin D analogues', 'methotrexate', 'biologics'], 'moderate', false, 0.00),
('Eczema (Atopic Dermatitis)', 'Condition that makes skin red and itchy.', ARRAY['dry skin', 'severe itching', 'red to brownish-gray patches', 'small raised bumps', 'thickened cracked skin', 'raw sensitive skin'], ARRAY['moisturize regularly', 'identify triggers', 'take shorter showers', 'use gentle soaps'], ARRAY['corticosteroid creams', 'calcineurin inhibitors', 'antihistamines'], 'mild', false, 0.00),
('Acne Vulgaris', 'Skin condition that occurs when hair follicles plug with oil.', ARRAY['whiteheads', 'blackheads', 'small red tender bumps', 'pimples', 'large solid painful lumps beneath skin', 'cystic lesions'], ARRAY['wash face twice daily', 'use non-comedogenic products', 'avoid touching face'], ARRAY['benzoyl peroxide', 'salicylic acid', 'topical retinoids', 'oral antibiotics', 'isotretinoin'], 'mild', false, 0.00),
('Rosacea', 'Common skin condition causing redness and visible blood vessels.', ARRAY['facial redness', 'swollen red bumps', 'eye problems', 'enlarged nose'], ARRAY['avoid triggers like spicy food or alcohol', 'wear sunscreen'], ARRAY['brimonidine gel', 'azelaic acid', 'metronidazole', 'oral antibiotics'], 'mild', false, 0.00),

-- NEUROLOGICAL
('Migraine', 'Neurological condition causing severe recurring headaches.', ARRAY['throbbing headache', 'nausea', 'vomiting', 'extreme sensitivity to light', 'sensitivity to sound', 'visual aura', 'dizziness'], ARRAY['identify triggers', 'regular sleep', 'manage stress', 'limit caffeine'], ARRAY['sumatriptan', 'rizatriptan', 'ibuprofen', 'topiramate'], 'moderate', false, 0.00),
('Meningitis', 'Inflammation of membranes surrounding brain and spinal cord.', ARRAY['sudden severe headache', 'stiff neck', 'sudden high fever', 'sensitivity to light', 'confusion', 'nausea', 'vomiting', 'seizures', 'skin rash'], ARRAY['vaccination', 'avoid sharing utensils', 'wash hands'], ARRAY['intravenous antibiotics', 'ceftriaxone', 'dexamethasone'], 'critical', true, 0.25),
('Epilepsy', 'Central nervous system disorder.', ARRAY['temporary confusion', 'staring spell', 'stiff muscles', 'uncontrollable jerking movements', 'loss of consciousness', 'fear', 'anxiety'], ARRAY['take medication exactly as prescribed', 'get enough sleep', 'avoid triggers'], ARRAY['levetiracetam', 'valproic acid', 'lamotrigine', 'carbamazepine'], 'severe', false, 0.00),
('Parkinsons Disease', 'Progressive nervous system disorder.', ARRAY['tremor', 'slowed movement', 'rigid muscles', 'impaired posture and balance', 'loss of automatic movements', 'speech changes', 'writing changes'], ARRAY['regular aerobic exercise', 'physical therapy', 'occupational therapy'], ARRAY['levodopa', 'carbidopa', 'dopamine agonists', 'MAO B inhibitors'], 'severe', false, 0.00),
('Multiple Sclerosis', 'Disease in which the immune system eats away at protective nerve covering.', ARRAY['numbness or weakness', 'electric-shock sensations', 'tremor', 'lack of coordination', 'unsteady gait', 'vision problems', 'slurred speech', 'fatigue', 'dizziness'], ARRAY['get plenty of rest', 'exercise regularly', 'avoid heat'], ARRAY['corticosteroids', 'plasma exchange', 'ocrelizumab', 'interferon beta'], 'severe', false, 0.00),
('Alzheimers Disease', 'Progressive disorder causing brain cells to waste away.', ARRAY['memory loss', 'difficulty thinking and reasoning', 'making judgments and decisions', 'planning and performing familiar tasks', 'changes in personality and behavior'], ARRAY['regular exercise', 'social engagement', 'mental stimulation'], ARRAY['donepezil', 'rivastigmine', 'galantamine', 'memantine'], 'critical', false, 0.00),

-- CARDIOVASCULAR & METABOLIC
('Type 2 Diabetes', 'Chronic condition affecting blood sugar regulation.', ARRAY['increased thirst', 'frequent urination', 'increased hunger', 'extreme fatigue', 'blurred vision', 'slow healing of sores', 'frequent infections', 'numbness or tingling'], ARRAY['eat healthy', 'exercise regularly', 'monitor blood sugar', 'maintain weight'], ARRAY['metformin', 'sitagliptin', 'empagliflozin', 'insulin'], 'moderate', false, 0.00),
('Type 1 Diabetes', 'Chronic condition where pancreas produces little or no insulin.', ARRAY['increased thirst', 'frequent urination', 'bed-wetting in children', 'extreme hunger', 'unintended weight loss', 'irritability', 'fatigue', 'weakness', 'blurred vision'], ARRAY['monitor blood sugar closely', 'count carbohydrates', 'regular exercise'], ARRAY['insulin (short-acting, rapid-acting, long-acting)'], 'severe', false, 0.00),
('Hypertension', 'Persistently elevated blood pressure.', ARRAY['often asymptomatic', 'severe headache', 'shortness of breath', 'nosebleeds', 'flushing', 'dizziness', 'chest pain', 'visual changes'], ARRAY['reduce sodium', 'exercise', 'maintain weight', 'limit alcohol', 'manage stress'], ARRAY['amlodipine', 'lisinopril', 'losartan', 'hydrochlorothiazide'], 'moderate', false, 0.00),
('Coronary Artery Disease', 'Damage or disease in the hearts major blood vessels.', ARRAY['chest pain (angina)', 'shortness of breath', 'heart attack', 'fatigue', 'pain in arms or shoulder'], ARRAY['quit smoking', 'control blood pressure', 'check cholesterol', 'eat heart-healthy diet', 'exercise'], ARRAY['aspirin', 'beta blockers', 'nitroglycerin', 'statins', 'ACE inhibitors'], 'severe', false, 0.00),
('Heart Failure', 'Chronic condition where the heart doesnt pump blood as well as it should.', ARRAY['shortness of breath', 'fatigue', 'weakness', 'swelling in legs', 'swelling in ankles', 'swelling in feet', 'rapid or irregular heartbeat', 'reduced ability to exercise', 'persistent cough'], ARRAY['limit sodium', 'limit fluids', 'weigh yourself daily', 'avoid alcohol'], ARRAY['ACE inhibitors', 'beta blockers', 'diuretics', 'aldosterone antagonists'], 'critical', false, 0.00),
('Hyperthyroidism', 'Overactive thyroid.', ARRAY['unintentional weight loss', 'rapid heartbeat', 'irregular heartbeat', 'palpitations', 'increased appetite', 'nervousness', 'anxiety', 'irritability', 'tremor', 'sweating'], ARRAY['get enough calcium and vitamin D', 'manage stress'], ARRAY['methimazole', 'propylthiouracil', 'beta blockers', 'radioactive iodine'], 'moderate', false, 0.00),
('Hypothyroidism', 'Underactive thyroid.', ARRAY['fatigue', 'increased sensitivity to cold', 'constipation', 'dry skin', 'weight gain', 'puffy face', 'hoarseness', 'muscle weakness', 'elevated blood cholesterol level', 'muscle aches'], ARRAY['take medication consistently', 'eat balanced diet'], ARRAY['levothyroxine'], 'moderate', false, 0.00),
('Obesity', 'Complex disease involving an excessive amount of body fat.', ARRAY['excess body fat', 'shortness of breath', 'snoring', 'trouble sleeping', 'skin problems', 'inability to perform sudden physical tasks', 'feeling tired', 'joint pain'], ARRAY['dietary changes', 'exercise', 'behavioral changes'], ARRAY['orlistat', 'liraglutide', 'phentermine', 'bariatric surgery'], 'moderate', false, 0.00),

-- SYSTEMIC & OTHER
('Urinary Tract Infection (UTI)', 'Infection in urinary system.', ARRAY['strong persistent urge to urinate', 'burning sensation when urinating', 'frequent small amounts of urine', 'cloudy urine', 'red or pink urine', 'strong-smelling urine', 'pelvic pain'], ARRAY['drink water', 'urinate after sex', 'wipe front to back'], ARRAY['nitrofurantoin', 'trimethoprim-sulfamethoxazole', 'ciprofloxacin'], 'mild', false, 0.00),
('Kidney Stones', 'Hard deposits of minerals and salts inside kidneys.', ARRAY['severe sharp pain in side and back', 'pain radiating to lower abdomen', 'pain comes in waves', 'burning during urination', 'pink or brown urine', 'nausea', 'vomiting'], ARRAY['drink plenty of water', 'limit salt', 'limit animal protein'], ARRAY['ibuprofen', 'ketorolac', 'tamsulosin', 'potassium citrate'], 'severe', false, 0.00),
('Anemia', 'Deficiency of healthy red blood cells.', ARRAY['fatigue', 'weakness', 'pale skin', 'shortness of breath', 'dizziness', 'cold hands and feet', 'irregular heartbeat', 'chest pain', 'headache'], ARRAY['eat iron-rich foods', 'consume vitamin C'], ARRAY['ferrous sulfate', 'folic acid', 'vitamin B12'], 'moderate', false, 0.00),
('Gout', 'Form of inflammatory arthritis.', ARRAY['intense joint pain', 'lingering discomfort', 'inflammation', 'redness', 'limited range of motion', 'heat in joint'], ARRAY['limit alcohol', 'limit purine-rich foods', 'stay hydrated'], ARRAY['NSAIDs', 'colchicine', 'corticosteroids', 'allopurinol'], 'moderate', false, 0.00),
('Rheumatoid Arthritis', 'Chronic inflammatory disorder affecting joints.', ARRAY['tender warm swollen joints', 'joint stiffness usually worse in mornings', 'fatigue', 'fever', 'loss of appetite'], ARRAY['exercise regularly', 'apply heat or cold', 'relax', 'assistive devices'], ARRAY['NSAIDs', 'corticosteroids', 'DMARDs (methotrexate)', 'biologics'], 'severe', false, 0.00),
('Osteoarthritis', 'Degenerative joint disease.', ARRAY['pain in joints', 'stiffness', 'tenderness', 'loss of flexibility', 'grating sensation', 'bone spurs', 'swelling'], ARRAY['maintain healthy weight', 'exercise', 'hot and cold therapy'], ARRAY['acetaminophen', 'NSAIDs', 'duloxetine', 'cortisone injections'], 'moderate', false, 0.00),
('Osteoporosis', 'Bones become weak and brittle.', ARRAY['back pain', 'loss of height over time', 'stooped posture', 'bone fracture that occurs much more easily than expected'], ARRAY['calcium and vitamin D', 'exercise', 'quit smoking', 'limit alcohol'], ARRAY['bisphosphonates', 'denosumab', 'hormone therapy'], 'moderate', false, 0.00),
('Endometriosis', 'Tissue similar to the lining of the uterus grows outside the uterus.', ARRAY['painful periods', 'pain with intercourse', 'pain with bowel movements or urination', 'excessive bleeding', 'infertility', 'fatigue', 'diarrhea', 'constipation'], ARRAY['warm baths', 'heating pad', 'exercise'], ARRAY['pain relievers', 'hormone therapy', 'contraceptives'], 'moderate', false, 0.00),
('Polycystic Ovary Syndrome (PCOS)', 'Hormonal disorder causing enlarged ovaries with small cysts.', ARRAY['irregular periods', 'excess androgen', 'polycystic ovaries', 'weight gain', 'thinning hair', 'darkening of skin', 'acne'], ARRAY['weight loss', 'limit carbohydrates', 'be active'], ARRAY['birth control pills', 'metformin', 'clomiphene', 'spironolactone'], 'moderate', false, 0.00),
('Depression', 'Mood disorder causing a persistent feeling of sadness.', ARRAY['feelings of sadness', 'angry outbursts', 'loss of interest in activities', 'sleep disturbances', 'tiredness', 'reduced appetite', 'anxiety', 'slowed thinking'], ARRAY['get enough sleep', 'eat healthy', 'regular exercise', 'avoid alcohol'], ARRAY['SSRIs', 'SNRIs', 'TCAs', 'psychotherapy'], 'severe', false, 0.00),
('Generalized Anxiety Disorder', 'Severe ongoing anxiety that interferes with daily activities.', ARRAY['persistent worrying', 'overthinking', 'perceiving situations as threatening', 'difficulty handling uncertainty', 'indecisiveness', 'inability to set aside worry', 'restlessness', 'fatigue'], ARRAY['keep physically active', 'avoid alcohol and recreational drugs', 'quit smoking', 'cut back on caffeine'], ARRAY['antidepressants', 'buspirone', 'benzodiazepines', 'psychotherapy'], 'moderate', false, 0.00),
('Bipolar Disorder', 'Mental health condition causing extreme mood swings.', ARRAY['abnormally upbeat', 'increased activity', 'exaggerated sense of well-being', 'decreased need for sleep', 'unusual talkativeness', 'racing thoughts', 'distractibility', 'depressive episodes'], ARRAY['stick to a routine', 'avoid alcohol and drugs', 'manage stress'], ARRAY['lithium', 'valproic acid', 'antipsychotics', 'antidepressants'], 'severe', false, 0.00),
('Schizophrenia', 'Serious mental disorder in which people interpret reality abnormally.', ARRAY['delusions', 'hallucinations', 'disorganized thinking', 'extremely disorganized or abnormal motor behavior', 'negative symptoms', 'lack of emotion'], ARRAY['stick with treatment plan', 'learn about the disorder', 'stay focused on goals', 'avoid alcohol and drugs'], ARRAY['antipsychotics', 'psychotherapy', 'coordinated specialty care'], 'critical', false, 0.00),
('Tonsillitis', 'Inflammation of the tonsils.', ARRAY['red swollen tonsils', 'white or yellow coating on tonsils', 'sore throat', 'difficult or painful swallowing', 'fever', 'enlarged tender glands in neck', 'scratchy voice', 'bad breath'], ARRAY['get plenty of rest', 'drink adequate fluids', 'provide comforting foods', 'gargle with saltwater'], ARRAY['penicillin', 'amoxicillin', 'ibuprofen', 'acetaminophen'], 'mild', true, 0.40),
('Conjunctivitis (Pink Eye)', 'Inflammation of the transparent membrane that lines your eyelid.', ARRAY['redness in one or both eyes', 'itchiness in one or both eyes', 'gritty feeling in eyes', 'discharge in eyes that forms a crust', 'tearing'], ARRAY['dont touch your eyes', 'wash hands often', 'use clean towel', 'change pillowcases'], ARRAY['antibiotic eyedrops', 'antiviral medications', 'artificial tears'], 'mild', true, 0.80),
('Gastroesophageal Reflux Disease (GERD)', 'Digestive disease in which stomach acid irritates the food pipe lining.', ARRAY['heartburn', 'chest pain', 'difficulty swallowing', 'regurgitation of food or sour liquid', 'sensation of lump in throat'], ARRAY['maintain a healthy weight', 'stop smoking', 'elevate head of bed', 'dont lie down after a meal', 'eat food slowly'], ARRAY['antacids', 'H2 blockers', 'proton pump inhibitors'], 'moderate', false, 0.00),
('Hemorrhoids', 'Swollen and inflamed veins in the rectum and anus.', ARRAY['painless bleeding during bowel movements', 'itching or irritation in anal region', 'pain or discomfort', 'swelling around anus', 'lump near anus'], ARRAY['eat high-fiber foods', 'drink plenty of fluids', 'consider fiber supplements', 'dont strain', 'go as soon as you feel the urge'], ARRAY['over-the-counter creams', 'hydrocortisone suppositories', 'witch hazel'], 'mild', false, 0.00),
('Gallstones', 'Hardened deposits of digestive fluid that can form in your gallbladder.', ARRAY['sudden and rapidly intensifying pain in upper right abdomen', 'pain in center of abdomen', 'back pain between shoulder blades', 'pain in right shoulder', 'nausea or vomiting'], ARRAY['dont skip meals', 'lose weight slowly', 'eat more high-fiber foods', 'maintain a healthy weight'], ARRAY['cholecystectomy', 'medications to dissolve gallstones'], 'severe', false, 0.00),
('Herpes Simplex', 'Viral infection causing contagious sores, most often around the mouth or on the genitals.', ARRAY['pain or itching', 'small red bumps or tiny white blisters', 'ulcers', 'scabs'], ARRAY['use condoms', 'avoid sexual contact during outbreak', 'limit number of sexual partners'], ARRAY['acyclovir', 'valacyclovir', 'famciclovir'], 'moderate', true, 0.60),
('Chlamydia', 'Common sexually transmitted infection.', ARRAY['painful urination', 'vaginal discharge', 'discharge from penis', 'painful sexual intercourse', 'bleeding between periods', 'testicular pain'], ARRAY['use condoms', 'limit number of sex partners', 'get regular screenings'], ARRAY['azithromycin', 'doxycycline'], 'moderate', true, 0.70),
('Gonorrhea', 'Sexually transmitted infection.', ARRAY['painful urination', 'pus-like discharge from tip of penis', 'pain or swelling in one testicle', 'increased vaginal discharge', 'vaginal bleeding between periods', 'abdominal pain'], ARRAY['use condoms', 'limit number of sex partners', 'get regular gonorrhea screening'], ARRAY['ceftriaxone', 'azithromycin'], 'moderate', true, 0.70),
('Syphilis', 'Bacterial infection usually spread by sexual contact.', ARRAY['painless sore on genitals rectum or mouth', 'rash', 'muscle aches', 'fever', 'sore throat', 'swollen lymph nodes', 'hair loss', 'weight loss', 'fatigue'], ARRAY['abstain from sex', 'use latex condoms', 'avoid recreational drugs'], ARRAY['penicillin'], 'severe', true, 0.60),
('HIV/AIDS', 'Virus that attacks the bodys immune system.', ARRAY['fever', 'headache', 'muscle aches', 'joint pain', 'rash', 'sore throat', 'painful mouth sores', 'swollen lymph glands', 'diarrhea', 'weight loss'], ARRAY['use treatment as prevention', 'use post-exposure prophylaxis', 'use new condom every time', 'consider pre-exposure prophylaxis'], ARRAY['antiretroviral therapy (ART)', 'NNRTIs', 'NRTIs', 'PIs', 'INSTIs'], 'critical', true, 0.40),
('Rabies', 'Deadly virus spread to people from the saliva of infected animals.', ARRAY['fever', 'headache', 'nausea', 'vomiting', 'agitation', 'anxiety', 'confusion', 'hyperactivity', 'difficulty swallowing', 'excessive salivation', 'fear of water', 'hallucinations', 'insomnia', 'partial paralysis'], ARRAY['vaccinate your pets', 'keep pets confined', 'protect small pets from predators', 'report stray animals to local authorities', 'dont approach wild animals'], ARRAY['rabies immune globulin', 'rabies vaccine'], 'critical', false, 0.00),
('Tetanus', 'Serious bacterial infection that causes painful muscle spasms.', ARRAY['spasms and stiffness in your jaw muscles', 'stiffness of your neck muscles', 'difficulty swallowing', 'stiffness of your abdominal muscles', 'painful body spasms', 'fever', 'sweating', 'elevated blood pressure', 'rapid heart rate'], ARRAY['get vaccinated', 'clean wounds thoroughly', 'use antibiotics'], ARRAY['tetanus antitoxin', 'antibiotics', 'vaccine', 'sedatives'], 'critical', false, 0.00),
('Leukemia', 'Cancer of the bodys blood-forming tissues.', ARRAY['fever', 'chills', 'persistent fatigue', 'weakness', 'frequent or severe infections', 'losing weight without trying', 'swollen lymph nodes', 'enlarged liver or spleen', 'easy bleeding or bruising', 'recurrent nosebleeds', 'tiny red spots in your skin', 'excessive sweating', 'bone pain or tenderness'], ARRAY['avoid exposure to high doses of radiation', 'avoid exposure to certain chemicals', 'quit smoking'], ARRAY['chemotherapy', 'targeted therapy', 'radiation therapy', 'bone marrow transplant'], 'critical', false, 0.00),
('Breast Cancer', 'Cancer that forms in the cells of the breasts.', ARRAY['breast lump or thickening', 'change in size or shape of breast', 'changes to the skin over the breast', 'newly inverted nipple', 'peeling scaling crusting or flaking of the pigmented area of skin surrounding the nipple', 'redness or pitting of the skin over your breast'], ARRAY['ask your doctor about breast cancer screening', 'become familiar with your breasts', 'drink alcohol in moderation', 'exercise most days of the week', 'limit postmenopausal hormone therapy', 'maintain a healthy weight', 'choose a healthy diet'], ARRAY['surgery', 'radiation therapy', 'chemotherapy', 'hormone therapy', 'targeted therapy drugs'], 'severe', false, 0.00),
('Lung Cancer', 'Cancer that begins in the lungs.', ARRAY['new cough that doesnt go away', 'coughing up blood', 'shortness of breath', 'chest pain', 'hoarseness', 'losing weight without trying', 'bone pain', 'headache'], ARRAY['dont smoke', 'stop smoking', 'avoid secondhand smoke', 'test your home for radon', 'avoid carcinogens at work', 'eat a diet full of fruits and vegetables', 'exercise most days of the week'], ARRAY['surgery', 'radiation therapy', 'chemotherapy', 'targeted drug therapy', 'immunotherapy'], 'critical', false, 0.00),
('Prostate Cancer', 'Cancer that occurs in the prostate.', ARRAY['trouble urinating', 'decreased force in the stream of urine', 'blood in the urine', 'blood in the semen', 'bone pain', 'losing weight without trying', 'erectile dysfunction'], ARRAY['choose a healthy diet full of fruits and vegetables', 'choose healthy foods over supplements', 'exercise most days of the week', 'maintain a healthy weight', 'talk to your doctor about increased risk'], ARRAY['surgery', 'radiation therapy', 'hormone therapy', 'freezing prostate tissue', 'chemotherapy', 'immunotherapy', 'targeted drug therapy'], 'severe', false, 0.00),
('Colorectal Cancer', 'Cancer that begins in the large intestine.', ARRAY['persistent change in your bowel habits', 'rectal bleeding', 'blood in your stool', 'persistent abdominal discomfort', 'feeling that your bowel doesnt empty completely', 'weakness', 'fatigue', 'unexplained weight loss'], ARRAY['get screened for colon cancer', 'eat a variety of fruits vegetables and whole grains', 'drink alcohol in moderation if at all', 'stop smoking', 'exercise most days of the week', 'maintain a healthy weight'], ARRAY['surgery', 'chemotherapy', 'radiation therapy', 'targeted drug therapy', 'immunotherapy'], 'severe', false, 0.00),
('Melanoma', 'Most serious type of skin cancer.', ARRAY['large brownish spot with darker speckles', 'mole that changes in color size or feel or that bleeds', 'small lesion with an irregular border and portions that appear red pink white blue or blue-black', 'painful lesion that itches or burns', 'dark lesions on your palms soles fingertips or toes or on mucous membranes lining your mouth nose vagina or anus'], ARRAY['avoid the sun during the middle of the day', 'wear sunscreen year-round', 'wear protective clothing', 'avoid tanning beds', 'become familiar with your skin'], ARRAY['surgery', 'immunotherapy', 'targeted therapy', 'radiation therapy', 'chemotherapy'], 'severe', false, 0.00);

-- MOCK DISEASE REPORTS FOR DASHBOARD MAP
DO $$
DECLARE
  disease_1 UUID;
  disease_2 UUID;
  disease_3 UUID;
BEGIN
  SELECT id INTO disease_1 FROM public.diseases WHERE name = 'COVID-19' LIMIT 1;
  SELECT id INTO disease_2 FROM public.diseases WHERE name = 'Dengue Fever' LIMIT 1;
  SELECT id INTO disease_3 FROM public.diseases WHERE name = 'Asthma' LIMIT 1;

  IF disease_1 IS NOT NULL THEN
    INSERT INTO public.disease_reports (disease_id, symptoms_reported, location_lat, location_lng, city, state, confidence_score, reported_at)
    SELECT disease_1, ARRAY['dry cough','fever','loss of smell','fatigue'],
           28.7041 + (random()-0.5)*0.4, 77.1025 + (random()-0.5)*0.4,
           'Delhi', 'Delhi', 80 + random()*15, NOW() - (random()*7 || ' days')::interval
    FROM generate_series(1,40);
  END IF;
  
  IF disease_2 IS NOT NULL THEN
    INSERT INTO public.disease_reports (disease_id, symptoms_reported, location_lat, location_lng, city, state, confidence_score, reported_at)
    SELECT disease_2, ARRAY['sudden high fever','headache','joint pain','skin rash'],
           19.0760 + (random()-0.5)*0.5, 72.8777 + (random()-0.5)*0.5,
           'Mumbai', 'Maharashtra', 78 + random()*20, NOW() - (random()*14 || ' days')::interval
    FROM generate_series(1,35);
  END IF;

  IF disease_3 IS NOT NULL THEN
    INSERT INTO public.disease_reports (disease_id, symptoms_reported, location_lat, location_lng, city, state, confidence_score, reported_at)
    SELECT disease_3, ARRAY['wheezing','shortness of breath','chest tightness'],
           12.9716 + (random()-0.5)*0.4, 77.5946 + (random()-0.5)*0.4,
           'Bengaluru', 'Karnataka', 85 + random()*10, NOW() - (random()*10 || ' days')::interval
    FROM generate_series(1,20);
  END IF;
END $$;
